// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Icons = {
  AlertCircle: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.AlertCircle,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.ExclamationTriangleIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.AlertTriangle,
      }))
    ),
  },
  ArrowLeft: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.ArrowLeft,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.ArrowLeftIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.ArrowLeft,
      }))
    ),
  },
  ArrowRight: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.ArrowRight,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.ArrowRightIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.ArrowRight,
      }))
    ),
  },
  ArrowUpDown: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.ArrowUpDown,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.CaretSortIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.ArrowDown,
      }))
    ),
  },
  BellRing: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.BellRing,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.BellIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.Bell,
      }))
    ),
  },
  Bold: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.Bold,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.FontBoldIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.QuestionMarkCircle,
      }))
    ),
  },
  Calculator: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.Calculator,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.ComponentPlaceholderIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.QuestionMarkCircle,
      }))
    ),
  },
  Calendar: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.Calendar,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.CalendarIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.Calendar,
      }))
    ),
  },
  Check: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.Check,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.CheckIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.CheckMarkCircle2,
      }))
    ),
  },
  ChevronDown: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.ChevronDown,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.ChevronDownIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.ChevronDown,
      }))
    ),
  },
  ChevronLeft: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.ChevronLeft,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.ChevronLeftIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.ChevronLeft,
      }))
    ),
  },
  ChevronRight: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.ChevronRight,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.ChevronRightIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.ChevronRight,
      }))
    ),
  },
  ChevronUp: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.ChevronUp,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.ChevronUpIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.ChevronUp,
      }))
    ),
  },
  ChevronsUpDown: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.ChevronsUpDown,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.CaretSortIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.QuestionMarkCircle,
      }))
    ),
  },
  Circle: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.Circle,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.DotFilledIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.QuestionMarkCircle,
      }))
    ),
  },
  Copy: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.Copy,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.CopyIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.Copy,
      }))
    ),
  },
  CreditCard: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.CreditCard,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.ComponentPlaceholderIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.CreditCard,
      }))
    ),
  },
  GripVertical: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.GripVertical,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.DragHandleDots2Icon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.QuestionMarkCircle,
      }))
    ),
  },
  Italic: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.Italic,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.FontItalicIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.QuestionMarkCircle,
      }))
    ),
  },
  Loader2: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.Loader2,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.ReloadIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.Refresh,
      }))
    ),
  },
  Mail: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.Mail,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.EnvelopeClosedIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.Email,
      }))
    ),
  },
  MailOpen: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.MailOpen,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.EnvelopeOpenIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.QuestionMarkCircle,
      }))
    ),
  },
  Minus: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.Minus,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.MinusIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.Minus,
      }))
    ),
  },
  Moon: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.Moon,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.MoonIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.Moon,
      }))
    ),
  },
  MoreHorizontal: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.MoreHorizontal,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.DotsHorizontalIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.MoreHorizontal,
      }))
    ),
  },
  PanelLeft: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.PanelLeft,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.ViewVerticalIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.QuestionMarkCircle,
      }))
    ),
  },
  Plus: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.Plus,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.PlusIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.Plus,
      }))
    ),
  },
  Search: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.Search,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.MagnifyingGlassIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.Search,
      }))
    ),
  },
  Send: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.Send,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.PaperPlaneIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.PaperPlane,
      }))
    ),
  },
  Settings: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.Settings,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.GearIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.Settings,
      }))
    ),
  },
  Slash: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.Slash,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.SlashIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.Slash,
      }))
    ),
  },
  Smile: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.Smile,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.FaceIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.QuestionMarkCircle,
      }))
    ),
  },
  Sun: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.Sun,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.SunIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.Sun,
      }))
    ),
  },
  Terminal: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.Terminal,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.RocketIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.QuestionMarkCircle,
      }))
    ),
  },
  Underline: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.Underline,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.UnderlineIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.QuestionMarkCircle,
      }))
    ),
  },
  User: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.User,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.PersonIcon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.Person,
      }))
    ),
  },
  X: {
    lucide: React.lazy(() =>
      import("lucide-react").then((mod) => ({
        default: mod.X,
      }))
    ),
    radix: React.lazy(() =>
      import("@radix-ui/react-icons").then((mod) => ({
        default: mod.Cross2Icon,
      }))
    ),
    eva: React.lazy(() =>
      import("eva-icons").then((mod) => ({
        default: mod.CrossCircle,
      }))
    ),
  },
}
