export * from "./components/InformationCircleIcon"
export * from "./components/WarningErrorIcon"
export * from "./components/CheckCircleIcon"
export * from "./components/RemoveCircleIcon"
export * from "./components/ChevronDownIcon"
export * from "./components/AlignCenterIcon"
export * from "./components/AlignRightIcon"
export * from "./components/AlignLeftIcon"

export { default as InformationCircleIcon } from "./components/InformationCircleIcon"
export { default as WarningErrorIcon } from "./components/WarningErrorIcon"
export { default as CheckCircleIcon } from "./components/CheckCircleIcon"
export { default as RemoveCircleIcon } from "./components/RemoveCircleIcon"
export { default as ChevronDownIcon } from "./components/ChevronDownIcon"
export { default as AlignRightIcon } from "./components/AlignRightIcon"
export { default as AlignCenterIcon } from "./components/AlignCenterIcon"
export { default as AlignLeftIcon } from "./components/AlignLeftIcon"
